---
title: "Homework 2"
author: "Oliver Atwood + Dave Drennan + Trevor Kapuvari"
date: '2023-09-19'
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup clear environment, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

### Load packages and functions

```{r setup packages, warning = FALSE}
# Load Libraries

library(tidyverse)
library(tidycensus)
library(sf)
library(kableExtra)
library(RSocrata)
library(dplyr)
library(stringr)

# we don't want scientific notation
options(scipen=999)

# set default class to return the spatial data as sf objects by default
options(tigris_class = "sf")

# load custom functions from the book
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

palette5 <- c("#f0f9e8","#bae4bc","#7bccc4","#43a2ca","#0868ac")

census_api_key("e13d5be5cb48d927009e0dca0af99d21918d514f", overwrite = TRUE)

```


```{r tracts09}
tracts09 <- 
  get_acs(geography = "tract", 
          variables = c("B25026_001E","B02001_002E",
                        "B15001_050E","B15001_009E",
                        "B19013_001E","B25058_001E",
                        "B06012_002E"), 
          year=2009, state=06, county=c("001", "013", "041", "075", "081", "085", "095"), 
          geometry=TRUE, output="wide") %>%
  st_transform('EPSG:2227') %>%
  rename(TotalPop = B25026_001E, 
         Whites = B02001_002E,
         FemaleBachelors = B15001_050E, 
         MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, 
         MedRent = B25058_001E,
         TotalPoverty = B06012_002E) %>% 
  mutate(area = st_area(geometry)) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2009", density = (TotalPop / (area * 0.00000003587 ))) %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty) 

```

```{r tracts17}
tracts17 <- 
  get_acs(geography = "tract", 
          variables = c("B25026_001E","B02001_002E",
                        "B15001_050E","B15001_009E",
                        "B19013_001E","B25058_001E",
                        "B06012_002E"), 
          year=2017, state=06, county=c("001", "013", "041", "075", "081", "085", "095"), 
          geometry=TRUE, output="wide") %>%
  st_transform('EPSG:2227') %>%
  rename(TotalPop = B25026_001E, 
         Whites = B02001_002E,
         FemaleBachelors = B15001_050E, 
         MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, 
         MedRent = B25058_001E,
         TotalPoverty = B06012_002E) %>% 
  mutate(area = st_area(geometry)) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2017", density = (TotalPop / (area * 0.00000003587 ))) %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty) 
```



```{r bind tracts}

allTracts <- rbind(tracts09,tracts17)

#Crop
#allTracts <- st_crop(allTracts, xmin = 6025077, xmax = 5957122, ymin = 2080091, ymax = 2137110)
```

### Wrangling Transit Open Data

```{r Wrangle Transit Data}
BART_Stops <- st_read("https://raw.githubusercontent.com/olivegardener/musa_5080_2023/main/Week_2/data/BART_System.kml")

BART_Stops <- BART_Stops %>%
  st_transform(2227)

sf_outline <- st_union(tracts09)

# Find the points that are within the boundary
indices <- st_within(BART_Stops, sf_outline, sparse = FALSE)

# Create a new sf object containing only the points within the boundary
BART_Stops_SF <- BART_Stops[as.vector(indices), ]

```

```{r Crop Size}
#Buffer Bart stops for Bounding Box
Buffer4Crop <- st_union(st_buffer(BART_Stops_SF, (8*2640))) %>%
      st_sf() %>%
      mutate(Legend = "Crop Buffer")

# Get the bounding box of Buffer4Crop
bbox_Buffer4Crop <- st_bbox(Buffer4Crop)

# Crop allTracts using the bounding box of Buffer4Crop
cropped_allTracts <- st_crop(allTracts, bbox_Buffer4Crop)

```

```{r BART Stops Buffer}
BART_Stops_Buffers <- 
  rbind(
    st_buffer(BART_Stops_SF, 2640) %>%
      mutate(Legend = "Buffer") %>%
      dplyr::select(Legend),
    st_union(st_buffer(BART_Stops_SF, 2640)) %>%
      st_sf() %>%
      mutate(Legend = "Unioned Buffer"))
```

```{r buffer filter}
buffer <- filter(BART_Stops_Buffers, Legend =="Unioned Buffer")
```


```{r Select Centroids}
selectCentroids <-
  st_centroid(tracts09)[buffer,] %>%
  st_drop_geometry() %>%
  left_join(., dplyr::select(tracts09, GEOID), by = "GEOID") %>%
  st_sf() %>%
  dplyr::select(TotalPop, MedRent) %>%
  mutate(Selection_Type = "Select by Centroids")
```
```{r Stations with Tract Selection}
ggplot() +
  geom_sf(data=selectCentroids, aes(fill = TotalPop)) +
  geom_sf(data=BART_Stops_SF, show.legend = "point") +
  scale_fill_viridis_c() +
  mapTheme()
```


```{r Indicator Maps}
allTracts.group <- 
  rbind(
    st_centroid(allTracts)[buffer,] %>%
      st_drop_geometry() %>%
      left_join(allTracts) %>%
      st_sf() %>%
      mutate(TOD = "TOD"),
    st_centroid(allTracts)[buffer, op = st_disjoint] %>%
      st_drop_geometry() %>%
      left_join(allTracts) %>%
      st_sf() %>%
      mutate(TOD = "Non-TOD")) %>%
    mutate(MedRent.inf = ifelse(year == "2009", MedRent * 1.68, MedRent)) %>%
      st_join(BART_Stops)

# Should do for SF only, too large of an area to compare

ggplot(allTracts.group)+
    geom_sf(data = st_union(tracts17))+
    geom_sf(aes(fill = TOD)) +
    labs(title = "Time/Space Groups") +
    facet_wrap(~year)+
    mapTheme() + 
    theme(plot.title = element_text(size=22))

ggplot(allTracts.group)+
    geom_sf(data = st_union(tracts17))+
    geom_sf(aes(fill = TotalPop)) +
    labs(title = "Time/Space Groups") +
    facet_wrap(~year)+
    mapTheme() + 
    theme(plot.title = element_text(size=22))

ggplot(allTracts.group)+
    geom_sf(data = st_union(tracts17))+
    geom_sf(aes(fill = MedHHInc)) +
    labs(title = "Time/Space Groups") +
    facet_wrap(~year)+
    mapTheme() + 
    theme(plot.title = element_text(size=22))

ggplot(allTracts.group)+
    geom_sf(data = st_union(tracts17))+
    geom_sf(aes(fill = MedRent)) +
    labs(title = "Time/Space Groups") +
    facet_wrap(~year)+
    mapTheme() + 
    theme(plot.title = element_text(size=22))

ggplot(allTracts.group)+
    geom_sf(data = st_union(tracts17))+
    geom_sf(aes(fill = drop_units(density))) +
    labs(title = "Time/Space Groups") +
    facet_wrap(~year)+
    mapTheme() + 
    theme(plot.title = element_text(size=22))

```

### TOD Indicator Tables

```{r TOD Indicator Table}
allTracts.Summary <- 
  st_drop_geometry(allTracts.group) %>%
  group_by(year, TOD) %>%
  summarize(Rent = mean(MedRent, na.rm = T),
            Population = mean(TotalPop, na.rm = T),
            #Percent_White = mean(pctWhite, na.rm = T),
            Density = mean(density, na.rm = T),
            Percent_Poverty = mean(pctPoverty, na.rm = T))

kable(allTracts.Summary) %>%
  kable_styling() %>%
  footnote(general_title = "\n",
           general = "Table 2.2")
```

```{r kable table}
allTracts.Summary %>%
  unite(year.TOD, year, TOD, sep = ": ", remove = T) %>%
  gather(Variable, Value, -year.TOD) %>%
  mutate(Value = round(Value, 2)) %>%
  spread(year.TOD, Value) %>%
  kable() %>%
  kable_styling() %>%
  footnote(general_title = "\n",
           general = "Table 2.3")
```

### TOD Indicator Plots

```{r TOD indicator Plots}
allTracts.Summary %>%
  gather(Variable, Value, -year, -TOD) %>%
  ggplot(aes(year, Value, fill = TOD)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~Variable, scales = "free", ncol=5) +
  scale_fill_manual(values = c("#bae4bc", "#0868ac")) +
  labs(title = "Indicator differences across time and space") +
  plotTheme() + theme(legend.position="bottom")
```


```{r graduated symbol map }
Stops_Individual <- st_buffer(BART_Stops_SF, 2640)

graduated_stops <-
  st_join(Stops_Individual, st_centroid(cropped_allTracts)) %>%
  group_by(Name) %>%
  summarize(pop_0.5mi_sum = sum(TotalPop, na.rm = TRUE),
            rent_0.5mi_mean = round(mean(MedRent, na.rm = TRUE), digits = 0))
ggplot()+
  geom_sf(data = cropped_allTracts, fill = "white") +
  geom_sf(data = st_centroid(graduated_stops),
          aes(size = pop_0.5mi_sum)) +
  scale_size_continuous(range = c(0.1,4))

ggplot()+
  geom_sf(data = cropped_allTracts, fill = "white") +
  geom_sf(data = st_centroid(graduated_stops),
          aes(size = rent_0.5mi_mean)) +
  scale_size_continuous(range = c(0.1,4))
```  
  
### Example of using `multipleRingBuffer()` function

```{r multipleRingBuffer}
BART_MRB <- multipleRingBuffer(st_union(BART_Stops_SF), 47520, 2640)

allTracts.rings <-
  st_join(st_centroid(dplyr::select(allTracts, GEOID, year)),
          BART_MRB) %>%
  st_drop_geometry() %>%
  left_join(dplyr::select(allTracts, GEOID, MedRent, year), 
            by=c("GEOID"="GEOID", "year"="year")) %>%
  st_sf() %>%
  mutate(distance = distance / 5280) #convert to miles

allTracts.rings.summary <- st_drop_geometry(allTracts.rings) %>%
    group_by(distance, year) %>%
    summarize(Mean_Rent = mean(MedRent, na.rm=T))

ggplot(allTracts.rings.summary,
       aes(distance, Mean_Rent, colour=year)) +
      geom_point(size=3) + 
  geom_line(size=2)



```

