---
title: "MUSA508_Final"
author: "Oliver Atwood, Dave Drennan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}

library(tidyverse)
library(tidycensus)
library(sf)
library(kableExtra)
library(caret)
library(knitr) 
library(pscl)
library(plotROC)
library(pROC)
library(lubridate)
library(gridExtra)
library(cowplot)
library(raster)
library(sp)
library(FNN)

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

options(scipen = 999)

census_api_key("e13d5be5cb48d927009e0dca0af99d21918d514f")

palette5 <- c("#981FAC","#CB0F8B","#FF006A","#FE4C35","#FE9900")
palette4 <- c("#981FAC","#FF006A","#FE4C35","#FE9900")
palette2 <- c("#981FAC","#FF006A")

ileast <- "epsg:3435"

```

# Data

```{r inspections data}

inspections_all <- read_csv("Data/Food_Inspections_-_7_1_2018_-_Present.csv")

inspections_all$date <- mdy(inspections_all$`Inspection Date`)
inspections_all$year <- year(inspections_all$date)
inspections_all$quarter <- quarter(inspections_all$date)

inspections <- inspections_all %>%
  dplyr::filter(year == 2021 | year == 2022,
                Results != "No Entry" & Results != "Out of Business" & Results != "Not Ready",
                is.na(Location) == FALSE,
                is.na(Risk) == FALSE) %>%
  rename(insp_type = "Inspection Type") %>%
  mutate(Type = case_when( insp_type == "Canvass" ~ "Canvass",
                           insp_type == "Complaint" ~ "Complaint",
                           insp_type == "License" ~ "License",
                           insp_type == "Canvass Re-Inspection" |
                             insp_type == "Complaint Re-Inspection" |
                             insp_type == "License Re-Inspection" ~ "Re-Inspections",
                           insp_type == "NO ENTRY" |
                             insp_type == "Non-Inspection" |
                             insp_type == "Recent Inspection" |
                             insp_type == "Short Form Complaint" |
                             insp_type == "Special Events (Festivals)" |
                             insp_type == "Suspected Food Poisoning" |
                             insp_type == "Suspected Food Poisoning Re-inspection" ~ "Other"),
         fail_numeric = case_when(Results == "Pass" ~ 0,
                   Results == "Pass w/ Conditions" ~ 0,
                   Results != "Pass" ~ 1),
         fail = case_when(Results == "Pass" ~ "No",
                   Results == "Pass w/ Conditions" ~ "No",
                   Results != "Pass" ~ "Yes"),
         )

inspections <- inspections %>%
  st_as_sf(coords = c("Longitude", "Latitude")) %>%
  st_set_crs(4326) %>%
  st_transform(ileast)

#inspections <- write.csv(inspections_final)
```

```{r external data}

# 311 data
rats <- read_csv("Data/Data_311/rodent_baiting_rat_complaints.csv")
building_violations <- read_csv("Data/Data_311/building_violations.csv")
plumbing_violations <- read_csv("Data/Data_311/buildings_plumbing_violations.csv")
business_complaints <- read_csv("Data/Data_311/business_complaints.csv")
dumping <- read_csv("Data/Data_311/fly_dumping_complaints.csv")
carts <- read_csv("Data/Data_311/food_vendor_pushcart_complaints.csv")
low_water_pressure <- read_csv("Data/Data_311/low_water_pressure_complaints.csv")
permit_construction_violations <- read_csv("Data/Data_311/no_building_permits_construction_violations.csv")
no_water <- read_csv("Data/Data_311/no_water_complaints.csv")
nuisance_animals <- read_csv("Data/Data_311/nuisance_animal_complaints.csv")
sick_leave_violations <- read_csv("Data/Data_311/paid_sick_leave_violations.csv")
sanitation_violations <- read_csv("Data/Data_311/sanitation_code_violations.csv")
street_cleaning <- read_csv("Data/Data_311/street_cleaning_request.csv")
vacant_abandoned_complaints <- read_csv("Data/Data_311/vacant_abandoned_building_complaints.csv")
vicious_animals <- read_csv("Data/Data_311/vicious_animal_complaints.csv")
wage_complaints <- read_csv("Data/Data_311/wage_complaints.csv")
water_basement <- read_csv("Data/Data_311/water_in_basement_complaints.csv")
water_street <- read_csv("Data/Data_311/water_on_street_complaints.csv")
water_quality_concern <- read_csv("Data/Data_311/water_quality_concern.csv")

# Other open data
neighborhoods <- st_read("Data/neighborhoods.shp") %>%
  st_transform(ileast)
# liquor <- read_csv("Data/Total_Liquor_Licenses_in_Chicago.csv") %>%
#   st_as_sf(coords = c("LONGITUDE", "LATITUDE")) %>%
#   st_set_crs(4326) %>%
#   st_transform(ileast)


```

```{r feature engineering}

animal <- rbind(rats, nuisance_animals, vicious_animals) %>%
  dplyr::filter(is.na(LOCATION) != TRUE,
                STATUS != "Canceled",
                DUPLICATE == "FALSE") %>%
  st_as_sf(coords = c("LONGITUDE", "LATITUDE")) %>%
  st_set_crs(4326) %>%
  mutate(date = mdy_hms(CREATED_DATE)) %>%
  mutate(year = year(date)) %>%
  dplyr::select(SR_TYPE, year, geometry) %>%
  st_transform(ileast)


sanitation <- rbind(dumping, sanitation_violations, street_cleaning) %>%
  dplyr::filter(is.na(LOCATION) != TRUE,
                STATUS != "Canceled",
                DUPLICATE == "FALSE") %>%
  st_as_sf(coords = c("LONGITUDE", "LATITUDE")) %>%
  st_set_crs(4326) %>%
  mutate(date = mdy_hms(CREATED_DATE)) %>%
  mutate(year = year(date)) %>%
  dplyr::select(SR_TYPE, year, geometry) %>%
  st_transform(ileast)

building <- rbind(building_violations, plumbing_violations, permit_construction_violations, vacant_abandoned_complaints) %>%
  dplyr::filter(is.na(LOCATION) != TRUE,
                STATUS != "Canceled",
                DUPLICATE == "FALSE") %>%
  st_as_sf(coords = c("LONGITUDE", "LATITUDE")) %>%
  st_set_crs(4326) %>%
  mutate(date = mdy_hms(CREATED_DATE)) %>%
  mutate(year = year(date)) %>%
  dplyr::select(SR_TYPE, year, geometry) %>%
  st_transform(ileast)

flooding <- rbind(water_basement, water_street) %>%
  dplyr::filter(is.na(LOCATION) != TRUE,
                STATUS != "Canceled",
                DUPLICATE == "FALSE") %>%
  st_as_sf(coords = c("LONGITUDE", "LATITUDE")) %>%
  st_set_crs(4326) %>%
  mutate(date = mdy_hms(CREATED_DATE)) %>%
  mutate(year = year(date)) %>%
  dplyr::select(SR_TYPE, year, geometry) %>%
  st_transform(ileast)

water <- rbind(low_water_pressure, no_water) %>%
  dplyr::filter(is.na(LOCATION) != TRUE,
                STATUS != "Canceled",
                DUPLICATE == "FALSE") %>%
  st_as_sf(coords = c("LONGITUDE", "LATITUDE")) %>%
  st_set_crs(4326) %>%
  mutate(date = mdy_hms(CREATED_DATE)) %>%
  mutate(year = year(date)) %>%
  dplyr::select(SR_TYPE, year, geometry) %>%
  st_transform(ileast)

business <- rbind(business_complaints, carts, sick_leave_violations, wage_complaints) %>%
  dplyr::filter(is.na(LOCATION) != TRUE,
                STATUS != "Canceled",
                DUPLICATE == "FALSE") %>%
  st_as_sf(coords = c("LONGITUDE", "LATITUDE")) %>%
  st_set_crs(4326) %>%
  mutate(date = mdy_hms(CREATED_DATE)) %>%
  mutate(year = year(date)) %>%
  dplyr::select(SR_TYPE, year, geometry) %>%
  st_transform(ileast)

inspections_features <- inspections %>%
  st_join(., neighborhoods) %>%
  dplyr::select(-sec_neigh, -shape_area, -shape_len)%>%
  rename(neighborhood = "pri_neigh")


inspections_features <- inspections_features %>%
    mutate(
      animals_nn5 = nn_function(st_coordinates(inspections_features), 
                                     st_coordinates(st_centroid(animal)), 
                                     k = 5),
      sanitation_nn5 = nn_function(st_coordinates(inspections_features), 
                                     st_coordinates(st_centroid(sanitation)), 
                                     k = 3),
      buildings_nn5 = nn_function(st_coordinates(inspections_features), 
                                     st_coordinates(st_centroid(building)), 
                                     k = 5),
      flooding_nn3 = nn_function(st_coordinates(inspections_features), 
                                     st_coordinates(st_centroid(flooding)), 
                                     k = 3),
      water_nn3 = nn_function(st_coordinates(inspections_features), 
                                     st_coordinates(st_centroid(water)), 
                                     k = 3),
      business_nn3 = nn_function(st_coordinates(inspections_features), 
                                     st_coordinates(st_centroid(business)), 
                                     k = 3)
      )


```

```{r get and join census data, message=FALSE, warning=FALSE, cache=TRUE, results = 'hide'}
chicagoCensus <- 
  get_acs(geography = "tract", 
          variables = c("B19013_001", "B25002_003", "B25001_001", "B25058_001", "B01003_001", "B17001_001"), 
          year = 2021, 
          state = "IL", 
          geometry = TRUE, 
          county=c("Cook"),
          output = "wide") %>%
  rename(Med_Inc = B19013_001E,
         Total_Vacancy = B25002_003E,
         Total_Units = B25001_001E,
         Med_Rent = B25058_001E) %>%
  mutate(Percent_Vacancy = Total_Vacancy / Total_Units * 100) %>% 
  dplyr::select(Med_Inc, Percent_Vacancy, Med_Rent, geometry) %>% 
  st_transform(ileast)

inspections_features <- st_join(inspections_features, chicagoCensus)

```


```{r extract raster data to points}
# Read the infrared data file
summer_thermal <- raster('Data/Landsat9_Thermal_Composite_Chicago.tif')
winter_thermal <- raster('Data/Landsat9_Thermal_Composite2_Chicago.tif')
pop_raster <- raster('Data/Pop_2020_Chicago.tif')


summer_thermal <- projectRaster(from = summer_thermal, crs = "+init=epsg:3435")
winter_thermal <- projectRaster(from = winter_thermal, crs = "+init=epsg:3435")
pop_raster <- projectRaster(from = pop_raster, crs = "+init=epsg:3435")

# Summer Thermal
# Extract raster values
extracted_values <- raster::extract(summer_thermal, inspections_features)
# Add the extracted values to the 'inspections' dataset
inspections_features$summer <- extracted_values

# Winter Thermal
extracted_values <- raster::extract(winter_thermal, inspections_features)
inspections_features$winter <- extracted_values

# Population
extracted_values <- raster::extract(pop_raster, inspections_features)
inspections_features$popdensity <- extracted_values


```


## Data Exploration

```{r maps}

inspections_map_data <- inspections_features %>%
  group_by(neighborhood) %>%
  summarize(total = n()) %>%
  st_drop_geometry()

neighborhoods <- neighborhoods %>%
  rename(neighborhood = "pri_neigh") %>%
  left_join(.,inspections_map_data,)

inspections_map <- ggplot() + 
  geom_sf(data = neighborhoods, aes(fill = total), color = "white", lwd = .8)+
  labs(title = "Inspections",
       caption = "Source: Chicago Data Portal") +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.title=element_text(size=16,face="bold", color = "white"),
        plot.subtitle = element_text(size=10,face="italic", color = "white"),
        plot.caption=element_text(size=8, color = "white"), 
        plot.background = element_rect(fill = 'black'))

a <- ggplot() + geom_sf(data = neighborhoods, fill = "black", color = "white", lwd = .8) +
  stat_density2d(data = data.frame(st_coordinates(animal)), 
                 aes(X, Y, fill = ..level.., alpha = ..level..),
                 size = 0.01, bins = 40, geom = 'polygon') +
  scale_fill_gradient(low = "lightyellow", high = "red",
                      name = "Density") +
  scale_alpha(range = c(0.00, 0.35), guide = FALSE) +
  labs(title = "311 Calls: Animals",
       subtitle = "Nuisance, Vicious, and Rodent",
       caption = "Source: Chicago Data Portal") +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.title=element_text(size=16,face="bold", color = "white"),
        plot.subtitle = element_text(size=10,face="italic", color = "white"),
        plot.caption=element_text(size=8, color = "white"), 
        plot.background = element_rect(fill = 'black'))

b <- ggplot() + geom_sf(data = neighborhoods, fill = "black", color = "white", lwd = .8) +
  stat_density2d(data = data.frame(st_coordinates(building)), 
                 aes(X, Y, fill = ..level.., alpha = ..level..),
                 size = 0.01, bins = 40, geom = 'polygon') +
  scale_fill_gradient(low = "lightyellow", high = "red",
                      name = "Density") +
  scale_alpha(range = c(0.00, 0.35), guide = FALSE) +
  labs(title = "311 Calls: Buildings",
       subtitle = "Violations - Construction, Permits, Vacant",
       caption = "Source: Chicago Data Portal") +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.title=element_text(size=16,face="bold", color = "white"),
        plot.subtitle = element_text(size=10,face="italic", color = "white"),
        plot.caption=element_text(size=8, color = "white"), 
        plot.background = element_rect(fill = 'black'))

c <- ggplot() + geom_sf(data = neighborhoods, fill = "black", color = "white", lwd = .8) +
  stat_density2d(data = data.frame(st_coordinates(business)), 
                 aes(X, Y, fill = ..level.., alpha = ..level..),
                 size = 0.01, bins = 40, geom = 'polygon') +
  scale_fill_gradient(low = "lightyellow", high = "red",
                      name = "Density") +
  scale_alpha(range = c(0.00, 0.35), guide = FALSE) +
  labs(title = "311 Calls: Businesses",
       subtitle = "Violations - Wages, Sick Leave, Complaints",
       caption = "Source: Chicago Data Portal") +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.title=element_text(size=16,face="bold", color = "white"),
        plot.subtitle = element_text(size=10,face="italic", color = "white"),
        plot.caption=element_text(size=8, color = "white"), 
        plot.background = element_rect(fill = 'black'))

d <- ggplot() + geom_sf(data = neighborhoods, fill = "black", color = "white", lwd = .8) +
  stat_density2d(data = data.frame(st_coordinates(water)), 
                 aes(X, Y, fill = ..level.., alpha = ..level..),
                 size = 0.01, bins = 40, geom = 'polygon') +
  scale_fill_gradient(low = "lightyellow", high = "red",
                      name = "Density") +
  scale_alpha(range = c(0.00, 0.35), guide = FALSE) +
  labs(title = "311 Calls: Water",
       subtitle = "No or Low Pressure",
       caption = "Source: Chicago Data Portal") +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.title=element_text(size=16,face="bold", color = "white"),
        plot.subtitle = element_text(size=10,face="italic", color = "white"),
        plot.caption=element_text(size=8, color = "white"), 
        plot.background = element_rect(fill = 'black'))

e <- ggplot() + geom_sf(data = neighborhoods, fill = "black", color = "white", lwd = .8) +
  stat_density2d(data = data.frame(st_coordinates(flooding)), 
                 aes(X, Y, fill = ..level.., alpha = ..level..),
                 size = 0.01, bins = 40, geom = 'polygon') +
  scale_fill_gradient(low = "lightyellow", high = "red",
                      name = "Density") +
  scale_alpha(range = c(0.00, 0.35), guide = FALSE) +
  labs(title = "311 Calls: Flooding",
       subtitle = "Street or Basement",
       caption = "Source: Chicago Data Portal") +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.title=element_text(size=16,face="bold", color = "white"),
        plot.subtitle = element_text(size=10,face="italic", color = "white"),
        plot.caption=element_text(size=8, color = "white"), 
        plot.background = element_rect(fill = 'black'))

f <- ggplot() + geom_sf(data = neighborhoods, fill = "black", color = "white", lwd = .8) +
  stat_density2d(data = data.frame(st_coordinates(sanitation)), 
                 aes(X, Y, fill = ..level.., alpha = ..level..),
                 size = 0.01, bins = 40, geom = 'polygon') +
  scale_fill_gradient(low = "lightyellow", high = "red",
                      name = "Density") +
  scale_alpha(range = c(0.00, 0.35), guide = FALSE) +
  labs(title = "311 Calls: Sanitation",
       subtitle = "Violations, Illegal Dumping, Street Cleaning",
       caption = "Source: Chicago Data Portal") +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.title=element_text(size=16,face="bold", color = "white"),
        plot.subtitle = element_text(size=10,face="italic", color = "white"),
        plot.caption=element_text(size=8, color = "white"), 
        plot.background = element_rect(fill = 'black'))

plot_row <- plot_grid(a, b, c, d, e, f, nrow = 2)

title <- ggdraw() + 
  draw_label(
    "311 Calls",
    fontface = 'bold',
    x = 0,
    hjust = .5
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )
plot_grid(
  title, plot_row,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)


a
b
c
d
e
f

wd <- getwd()
filename = file.path(wd, "img", "name.png")

```

```{r data vis}

inspections_features <- inspections_features %>%
  st_drop_geometry()

inspections %>%
    dplyr::select(fail, Risk, Type) %>%
    gather(Variable, value, -fail) %>%
    count(Variable, value, fail) %>%
      ggplot(., aes(value, n, fill = fail)) +   
        geom_bar(position = "dodge", stat="identity") +
        facet_wrap(~Variable, scales="free") +
        scale_fill_manual(values = palette2) +
        labs(x="Fail", y="Value",
             title = "Feature associations with the likelihood of Fail",
             subtitle = "Categorical features") +
        theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

## Feature Engineering

# Model

```{r create_partition}

inspections_2021 <- inspections %>%
  dplyr::filter(year == 2021)


set.seed(1234)
trainIndex <- createDataPartition(inspections_2021$fail, p = .50,
                                  list = FALSE,
                                  times = 1)
modelTrain <- inspections_2021[ trainIndex,]
modelTest  <- inspections_2021[-trainIndex,]

```

```{r run_model}

model <- glm(fail_numeric ~ .,
                  data=modelTrain %>% 
                    dplyr::select(fail_numeric, Risk, Type),
                  family="binomial" (link="logit"))

summary(model)

```
```{r testProbs}

testProbs <- data.frame(Outcome = as.factor(modelTest$fail_numeric),
                        Probs = predict(model, modelTest, type= "response"))

ggplot(testProbs, aes(x = Probs, fill = as.factor(Outcome))) + 
  geom_density() +
  facet_grid(Outcome ~ .) +
  scale_fill_manual(values = palette2) +
  labs(x = "Fail", y = "Density of probabilities",
       title = "Distribution of predicted probabilities by observed outcome") +
  theme(strip.text.x = element_text(size = 18),
        legend.position = "none")
```

```{r thresholds}
testProbs <- 
  testProbs %>%
  mutate(predOutcome  = as.factor(ifelse(testProbs$Probs > 0.5 , 1, 0)))
```

```{r confusion_matrix}
caret::confusionMatrix(testProbs$predOutcome, testProbs$Outcome, 
                       positive = "1")

```

```{r auc, message = FALSE, warning = FALSE}
auc(testProbs$Outcome, testProbs$Probs)
```
```{r roc_curve, warning = FALSE, message = FALSE}
ggplot(testProbs, aes(d = as.numeric(Outcome), m = Probs)) +
  geom_roc(n.cuts = 50, labels = FALSE, colour = "#FE9900") +
  style_roc(theme = theme_grey) +
  geom_abline(slope = 1, intercept = 0, size = 1.5, color = 'grey') +
  labs(title = "ROC Curve - Model")
```

```{r cv}
ctrl <- trainControl(method = "cv", number = 100, classProbs=TRUE, summaryFunction=twoClassSummary)

#Not running, "missing values in object"

cvFit <- train(fail ~ .,
                  data=inspections %>% 
                    dplyr::select(fail, Risk), 
                method="glm", family="binomial",
                metric="ROC", trControl = ctrl)

cvFit
```

```{r goodness_metrics, message = FALSE, warning = FALSE}
dplyr::select(cvFit$resample, -Resample) %>%
  gather(metric, value) %>%
  left_join(gather(cvFit$results[2:4], metric, mean)) %>%
  ggplot(aes(value)) + 
    geom_histogram(bins=35, fill = "#FF006A") +
    facet_wrap(~metric) +
    geom_vline(aes(xintercept = mean), colour = "#981FAC", linetype = 3, size = 1.5) +
    scale_x_continuous(limits = c(0, 1)) +
    labs(x="Goodness of Fit", y="Count", title="CV Goodness of Fit Metrics",
         subtitle = "Across-fold mean reprented as dotted lines")

```
