---
title: "PPA_Midterm"
author: "Oliver Atwood + Dave Drennan"
date: "2023-10-01"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())

knitr::opts_chunk$set(echo = TRUE)

root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

#some of these are repetitive with above - from Intro_to_ML_Pt`
library(ggplot2)
library(units)
library(httr)
library(rgdal)
library(corrplot)
library(tidyverse)
library(dplyr)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot) # plot correlation plot
library(corrr)      # another way to plot correlation plot
library(kableExtra)
library(jtools)     # for regression model plots
library(ggstance) # to support jtools plots
library(ggpubr)    # plotting R^2 value on ggplot point scatter
library(broom.mixed) # needed for effects plots
library(lubridate)

# Coordinate System
coordinate_system <- 2272

Sys.setenv(OGR_GEOJSON_MAX_OBJ_SIZE = "1000000")  # Set to a large value

```

### Load studentData
```{r warning=FALSE}
Houses <- st_read("data/studentData.geojson") %>%
  st_transform(crs = coordinate_system) %>% 
    dplyr::select(sale_price, basements, building_code_description, category_code_description, central_air, exterior_condition,
                  fireplaces, garage_spaces, interior_condition, number_of_bathrooms, number_of_bedrooms, number_of_rooms,
                  number_stories, quality_grade, sale_date, total_area, total_livable_area, type_heater, year_built, 
                  building_code_description_new, musaID, geometry) %>% 
    mutate(age = year_built-2023) %>% 
    dplyr::select(-year_built)

```

## Read wrangled data
```{r, message=FALSE}
##OA Local files
# TreeCanopy <- st_read("/Users/oliveratwood/Box Sync/PPA Midterm/data/TreeCanopy.geojson")
# landuse <- st_read("/Users/oliveratwood/Box Sync/PPA Midterm/data/Land_Use.geojson")%>%
#   st_transform(crs = coordinate_system)

# catchments <- st_read("data/School_Catchment/Catchment_ES_2021-22") %>% st_transform(crs = coordinate_system)
# Redlined <- st_read("data/redlining.geojson")
# Vacant_Lots <- st_read("data/Vacant_Lots.geojson")
# Recycling_Diversion_Rate <- st_read("data/Recycling_Diversion_Rate.geojson")
# Hospitals <- st_read("data/Hospitals.geojson")
# Regional_Rail_Stations <- st_read("data/Regional_Rail_Stations.geojson")
# Existing_Trails <- st_read("data/Existing_Trails.geojson")
# Traffic_Collisions <- st_read("data/PhillyHealth_Collisions.geojson")
# bike_network <- st_read("data/bike_network.geojson")
# parks <- st_read("data/parks.geojson")
# uni <- st_read("data/uni.geojson")
# neighborhoods <- st_read("data/neighborhoods.geojson")
# landcare_lots <- st_read("data/landcare_lots.geojson")
# tracts2020 <- st_read("data/tracts2020.geojson")
# septa <- st_read("data/septa.geojson")
# septa_bus <- septa %>% 
#   filter(mode == "Bus")
# septa_trolley <- septa %>% 
#   filter(mode == "Trolley")
# septa_highspeed <- septa %>% 
#   filter(mode == "Highspeed")
trees <- st_read("data/trees.geojson")

```

### Sample Data (for testing)
```{r}
# Sample Data for testing
n_sample <- round(nrow(Houses) * 0.01)
Houses <- Houses[sample(nrow(Houses), n_sample), ]
```

### Extract polygon data to points
```{r}
# Houses <- Houses %>% 
#           st_join(dplyr::select(Recycling_Diversion_Rate, SCORE)) %>% 
#           st_join(dplyr::select(neighborhoods, NAME)) %>%
#           st_join(dplyr::select(catchments, ES_Name)) %>%
#           st_join(dplyr::select(tracts2020, MedHHInc, MedRent, HomeOwnRate, PopDensity, PctWhite, PctBach, Car2WorkPct)) %>%
#           rename(RecyclingRate = SCORE,
#                  Neighborhood = NAME,
#                  MedHHInc_ACS = MedHHInc,
#                  MedRent_ACS = MedRent,
#                  PopDensity_ACS = PopDensity,
#                  PctWhite_ACS = PctWhite,
#                  PctBach_ACS = PctBach,
#                  Car2WorkPct_ACS = Car2WorkPct) %>% 
#           select(-HomeOwnRate)

```

### Compute min dist to trails and bike network
```{r}
# ## Trails
# # Compute distances
# distances <- st_distance(Houses, Existing_Trails)
# # Compute the minimum distance for each point to the nearest line
# min_distances <- apply(distances, 1, min)
# # Join the minimum distances to the attribute table of the points
# Houses$dist2trail <- min_distances
# 
# ## Bike Network
# distances <- st_distance(Houses, bike_network)
# min_distances <- apply(distances, 1, min)
# Houses$dist2bike <- min_distances
# 
# # Parks
# distances <- st_distance(Houses, parks)
# min_distances <- apply(distances, 1, min)
# Houses$dist2park <- min_distances

```

### Compute percent canopy cover within 500ft
```{r warning = FALSE}
# Create buffers around each house
HouseBuffers <- st_buffer(Houses, dist = (0.25*5280))

# Initialize an empty vector to store the canopy coverage percent for each house
CanopyPct100ft <- vector("numeric", length = nrow(Houses))

# Loop through each house buffer
for (i in 1:nrow(HouseBuffers)) {
# Calculate the intersection area between the current house buffer and the tree canopy
intersection_area <- sum(st_area(st_intersection(HouseBuffers[i, ], TreeCanopy)))

# Calculate the canopy coverage percent for the current house buffer
CanopyPct100ft[i] <- (intersection_area / st_area(HouseBuffers[i, ])) * 100}

# Add the canopy coverage percent values to the Houses data frame
Houses$CanopyPctQuMi <- CanopyPct100ft

```

### K nearest neighbors
```{r k nearest neighbors, warning=FALSE}
# Houses <- Houses %>%
#     mutate(hospitals_nn1 = nn_function(st_coordinates(Houses), 
#                               st_coordinates(Hospitals), k = 1),
#            rr_station_nn1 = nn_function(st_coordinates(Houses), 
#                               st_coordinates(Regional_Rail_Stations), k = 1),
#            septa_trolley_nn1 = nn_function(st_coordinates(Houses), 
#                               st_coordinates(septa_trolley), k = 1),
#            septa_bus_nn5 = nn_function(st_coordinates(Houses), 
#                               st_coordinates(septa_bus), k = 5), # look into this?
#            septa_highspeed_nn1 = nn_function(st_coordinates(Houses), 
#                               st_coordinates(septa_highspeed), k = 1),
#            collisions_nn3 = nn_function(st_coordinates(Houses), 
#                               st_coordinates(Traffic_Collisions), k = 3), #data old, keep?
#            unis_nn1 = nn_function(st_coordinates(Houses), 
#                               st_coordinates(st_centroid(uni)), k = 1),
#            landcare_lots_nn3 = nn_function(st_coordinates(Houses), 
#                               st_coordinates(st_centroid(landcare_lots)), k = 3),
#            vacant_lots_nn5 = nn_function(st_coordinates(Houses), 
#                               st_coordinates(st_centroid(Vacant_Lots)), k = 5)) %>% 
#     filter(sale_price != 0)

```

```{r}
st_write(Houses, "data/PhillyHouses.geojson", delete_dsn = TRUE)
```

