---
title: "OSM Data Wrangling"
output: html_document
date: "2023-09-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

## R Markdown

```{r cars}
# install.packages("osmdata")
library(osmdata)
library(sf)
library(ggplot2)
library(raster)
library(dplyr)
library(tidycensus)
library(units)
library(httr)
library(arcpullr)
library(tigris)
library(rgdal)

# Capture the start time
start_time <- Sys.time()
```

## Setting Parameters
```{r}
# Coordinate System
coordinate_system <- 2272

#Load Boundary File
philly_boundary <- counties(state = 42) %>% 
  filter(NAME == "Philadelphia")
# Create a bounding box from the boundary
bbox <- st_bbox(philly_boundary)

philly_boundary <- st_transform(philly_boundary, crs = coordinate_system)

```


```{r Geodatabase wrangling}
gdb_path <- "/Users/oliveratwood/Documents/GitHub/musa_5080_2023/Midterm/data/Features4PPA.gdb"
layers <- ogrListLayers(gdb_path)
print(layers)

Vacant_Lots <- sf::st_read(gdb_path, layer = "VacantLots")
Recycling_Diversion_Rate <- sf::st_read(gdb_path, layer = "Project_OutDataset_PhillyStreets_Recycling_Diversion_Rate")
Hospitals <- sf::st_read(gdb_path, layer = "Project_OutDataset_PhillyHealth_Hospitals")
Regional_Rail_Stations <- sf::st_read(gdb_path, layer = "Project_OutDataset_SEPTA___Regional_Rail_Stations")
TreeCanopy <- sf::st_read(gdb_path, layer = "Project_OutDataset_TreeCanopy2018_Dissolved")
Existing_Trails <- sf::st_read(gdb_path, layer = "Project_OutDataset_PhillyPlanning_Existing_Trails")
Trolley_Stops <- sf::st_read(gdb_path, layer = "Project_OutDataset_SEPTA___Trolley_Stops")
PhillyHealth_Collisions <- sf::st_read(gdb_path, layer = "Project_OutDataset_PhillyHealth_Collisions_crash_2011_2014PUBV")

```


```{r PhillyOpenData, fig.width=15}
#Uses arcpullr to access ESRI API - https://cran.r-project.org/web/packages/arcpullr/arcpullr.pdf

trees <- get_spatial_layer("https://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/PPR_Tree_Inventory_2022/FeatureServer/0/") %>%
  st_transform(crs = 2272)
bike_network <- get_spatial_layer("https://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/Bike_Network/FeatureServer/0/") %>% 
  st_transform(crs = 2272)
landuse <- get_spatial_layer("https://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/Land_Use/FeatureServer/0/")%>% 
  st_transform(crs = 2272)
parks <- get_spatial_layer("https://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/PPR_Properties/FeatureServer/0/")%>% 
  st_transform(crs = 2272)
uni <- get_spatial_layer("https://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/Universities_Colleges/FeatureServer/0/")%>% 
  st_transform(crs = 2272)
neighborhoods <- get_spatial_layer("https://services1.arcgis.com/a6oRSxEw6eIY5Zfb/ArcGIS/rest/services/Philadelphia_Neighborhoods/FeatureServer/0")%>%
  st_transform(crs = 2272)
septa <- get_spatial_layer("https://arcgis.dvrpc.org/portal/rest/services/Transportation/SEPTA_TransitStops/FeatureServer/0")%>% 
  st_transform(crs = 2272)
community_landcare <- get_spatial_layer("https://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/PHS_CommunityLandcare/FeatureServer/0/") %>% 
  st_transform(crs = 2272)
landcare_maintenance <- get_spatial_layer("https://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/PHS_PhilaLandCare_Maintenance/FeatureServer/0/") %>%
  st_transform(crs = 2272)

community_landcare <- st_centroid(community_landcare)
community_landcare <- st_geometry(community_landcare)
community_landcare <- st_sf(geometry = community_landcare)

landcare_maintenance <- st_centroid(landcare_maintenance)
landcare_maintenance <- st_geometry(landcare_maintenance)
landcare_maintenance <- st_sf(geometry = landcare_maintenance)

landcare_lots <- rbind(community_landcare, landcare_maintenance)

```


## ACS Data
```{r}

# For example, to get variables for the 2019 5-year ACS:
acs_vars <- load_variables(2020, "acs5", cache = TRUE)

# View the first few rows of the variables
print(acs_vars)

#2020 ACS data for Philly
tracts2020 <- 
  get_acs(geography = "tract", 
          variables = c("B25026_001E",
                        "B19013_001E",
                        "B25058_001E",
                        "DP04_0046PE",
                        "B02001_002E",
                        "B08137_004E",
                        "B25035_001E",
                        "B15003_022E"), 
          year=2020, state=42, county="101", 
          geometry=TRUE, output="wide") %>%
  st_transform(coordinate_system) %>%
  rename(TotalPop = B25026_001E, 
         MedHHInc = B19013_001E, 
         MedRent = B25058_001E,
         HomeOwnRate = DP04_0046PE,
         White = B02001_002E,
         Car2Work = B08137_004E,
         YrBuilt = B25035_001E,
         NumBach = B15003_022E) %>% 
  mutate(area = st_area(geometry)) %>%
  mutate(year = "2020", 
         PopDensity = drop_units((TotalPop / (area / 2.788e+7))),
         PctWhite = (White/TotalPop),
         PctBach = ifelse(TotalPop > 0, ((NumBach) / TotalPop), 0),
         HouseAge = (2020 - YrBuilt),
         Car2WorkPct = (Car2Work/TotalPop)*100) %>%
  dplyr::select(-NAME, -White, -NumBach, -YrBuilt, -Car2Work, -TotalPop, -area, -starts_with("D"), -starts_with("B"))
```

## OSM Data
```{r Download OSM Data, echo=FALSE}
# Download Roads Data from OSM
trunk <- opq(bbox) %>%
  add_osm_feature(key = "highway", value = "trunk") %>%
  osmdata_sf()
trunk <- trunk$osm_lines

trunk_link <- opq(bbox) %>%
  add_osm_feature(key = "highway", value = "trunk_link") %>%
  osmdata_sf()
trunk_link <- trunk_link$osm_lines

motorway <- opq(bbox) %>%
  add_osm_feature(key = "highway", value = "motorway") %>%
  osmdata_sf()
motorway <- motorway$osm_lines

motorway_link <- opq(bbox) %>%
  add_osm_feature(key = "highway", value = "motorway_link") %>%
  osmdata_sf()
motorway_link <- motorway_link$osm_lines

highways <- bind_rows(trunk, trunk_link, motorway, motorway_link)
highways <- st_transform(highways, coordinate_system)
highways <- st_intersection(highways, philly_boundary)

```

```{r}
st_write(Vacant_Lots, "data/Vacant_Lots.geojson", delete_dsn = TRUE)
st_write(Recycling_Diversion_Rate, "data/Recycling_Diversion_Rate.geojson", delete_dsn = TRUE)
st_write(Hospitals, "data/Hospitals.geojson", delete_dsn = TRUE)
st_write(Regional_Rail_Stations, "data/Regional_Rail_Stations.geojson", delete_dsn = TRUE)
st_write(TreeCanopy, "data/TreeCanopy.geojson", delete_dsn = TRUE)
st_write(Existing_Trails, "data/Existing_Trails.geojson", delete_dsn = TRUE)
st_write(Trolley_Stops, "data/Trolley_Stops.geojson", delete_dsn = TRUE)
st_write(PhillyHealth_Collisions, "data/PhillyHealth_Collisions.geojson", delete_dsn = TRUE)

st_write(trees, "data/trees.geojson", delete_dsn = TRUE)
st_write(bike_network, "data/bike_network.geojson", delete_dsn = TRUE)
st_write(landuse, "data/landuse.geojson", delete_dsn = TRUE)
st_write(parks, "data/parks.geojson", delete_dsn = TRUE)
st_write(uni, "data/uni.geojson", delete_dsn = TRUE)
st_write(neighborhoods, "data/neighborhoods.geojson", delete_dsn = TRUE)
st_write(septa, "data/septa.geojson", delete_dsn = TRUE)
st_write(landcare_lots, "data/landcare_lots.geojson", delete_dsn = TRUE)

st_write(highways, "data/highways.geojson", delete_dsn = TRUE)

st_write(tracts2020, "data/tracts2020.geojson", delete_dsn = TRUE)

```


### !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
### Calculate distances to features (non-KNN method, change vars as needed)
```{r }
# # Initialize an empty vector to store distances
# nearest_distances <- vector("numeric", length = nrow(Building_Pts))
# 
# # Loop through each centroid to find the nearest point in FIRST and calculate the distance
# for (i in 1:nrow(Building_Pts)) {
#   centroid <- Building_Pts[i, ]
#   nearest_index <- st_nearest_feature(centroid, highways)
#   nearest_point <- highways[nearest_index, ]
#   distance <- st_distance(centroid, nearest_point)
#   
# # Store the distance & convert to miles
# nearest_distances[i] <- as.numeric(distance/5280)}
# 
# # Add the distances to the cropped_allTracts_bay dataframe
# Buildings_Poly$Dist2Highway <- nearest_distances
```


```{r correlation matrix, fig.width=7, fig.height=5, fig.width=8}
# #make matrix of variables we're testing
# mod_vars <- Dat_A %>% 
#   dplyr::select(CHNG_URB, DIST_INTER, DIST_REGRA, DIST_RAILS, SLOPE, DIST_PARKS, REGRAIL300, INTERST800, MEDHSEVAL_, MEDINC90, PCT_POV_90)
# 
# #compute correlation matrix
# cormatrix <- cor(mod_vars) %>% 
#   round(., 2)
# 
# #plot a correlogram
# corrplot(cormatrix, method = "circle", type = "lower", order = "hclust", 
#          tl.col = "black", tl.srt = 45)
```


```{r timer_end}
# Capture the end time
end_time <- Sys.time()

# Calculate and print the runtime
runtime <- end_time - start_time
print(paste("Total runtime:", runtime))
```

